### ISSUE TITLE
FILO.c how to make it Circular

### ISSUE THREAD

**Issue by jcherrabi** [goToMain/c-utils#20]
Hello,
thanks for sharing, i was wondering if you can help, i would like to use the FILO.c and make it Circular buffer as well so when it's full the oldest value is overridden, similar to Circbuf.c, can you please help with that?

**Comment by sidcha** [comment]
Hey @jcherrabi, what is your goal there? (keeping in mind that filo.c has a list implementation of a queue).

You could just use circbuf.c if that's what you want :)
